[package]
name = "appdirs"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
description = "Rust crate for determining platform-specific directories"
repository = "https://github.com/djc/appdirs-rs"
license = "MIT"
